# Generated by Django 4.2 on 2024-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('draft', 'Черновик')], default='draft', max_length=200, verbose_name='Статус'),
        ),
    ]
