# Generated by Django 4.2 on 2024-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(help_text='Если установить дату в будущем — можно делать отложенные публикации.', verbose_name='Дата публикации'),
        ),
    ]
